[project]
name = "mcp-lite-dev"
version = "0.1.0"
description = "《MCP极简开发》项目代码"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "httpx>=0.28.1",
    "mcp>=1.10.1",
    "openai>=1.93.3",
    "pip>=25.1.1",
    "setuptools>=80.9.0",
    "wheel>=0.45.1",
]
